### ISSUE TITLE
List of features planned for 3.1

### ISSUE THREAD

**Issue by Username-N00b-is-not-available** [Realm667/WolfenDoom#519]
- [x] Remove DECORATE-specific hacks from translated ZScript actor code: https://github.com/Realm667/WolfenDoom/issues/470#issuecomment-817216404
- [x] Find a proper release version of GZDoom which would run Blade of Agony: https://github.com/Realm667/WolfenDoom/issues/499#issuecomment-826070408
- [x] Add warnings about 'jumping off' key binds to Customize Controls: https://github.com/Realm667/WolfenDoom/issues/512#issuecomment-826332412
- [x] Remove Nash's shadow mod from Blade of Agony: https://github.com/Realm667/WolfenDoom/issues/515#issue-867030742
- [x] Show statistics on surrendered enemies who were not killed by the player: https://github.com/Realm667/WolfenDoom/issues/518#issue-867035613
- [x] Lower MaxStepHeight to 32 for player tanks, so it is not possible to climb over enemy tanks on flat ground: https://github.com/Realm667/WolfenDoom/issues/384#issuecomment-826280738
- [x] Transition most of the ACS library to ZScript 
- [ ] Externalize hard-coded data for 'using' wall textures from scripts to a data/config file and generalize implementation
- [x] Fix all bugs we still have in issues
- [x] Include addons in the standalone zip release with the new launcher
- [x] Migrate ACS overlays to ZScript to mitigate resolution problems (see https://github.com/Realm667/WolfenDoom/tree/acsoverlays)
- [x] Localize and fix strange shader glitches: https://github.com/Realm667/WolfenDoom/issues/465, https://github.com/Realm667/WolfenDoom/issues/482
- [x] Fix enemy counts on stealth maps: #546
- [x] Fix problems mentioned by @Ozymandias81 here: https://github.com/Realm667/WolfenDoom/issues/542#issuecomment-830219183
- [x] Fix maps which break a non-cheating playthrough after `map cXmX_X` (e. g. you cannot finish C2M5_B if warped directly there, as the explosive charges are given in M5_A and not in M5_B; also true for the Firebrand and all maps after it, since you need to have it for C3M6_B. I don't remember if there are other ones)
- [x] **Move the `default` keyword to the English column in the CSV**. У семи нянек дитя без глазу, as it turned out.

:x: Merge some of the addons into the base game (namely `behaviour`, `more_weapons`, and `score`)? Add unused scrapped frames to actors (crouched firing)?

**Comment by Tormentor667** [comment]
Perfect, thanks for taking care!

**Comment by Ozymandias81** [comment]
I am not sure about "more weapons", but beside that we should also address [these](https://github.com/Realm667/WolfenDoom/issues/542#issuecomment-830219183)

**Comment by Username-N00b-is-not-available** [comment]
Well, that was just a suggestion :-) Added to first post.

**Comment by Username-N00b-is-not-available** [comment]
@AFADoomer There are some [comments](https://www.moddb.com/members/toomuchcoffee) on ModDB that express dissatisfaction with that you can move the combination safe handle to a position between two numbers, and it could not be easy to determine exactly which of the two numbers the safe will choose. Do you think if it could be reasonable to only do discrete +-1 number changes on the safe wheel with each key press?

**Comment by Tormentor667** [comment]
> 
> 
> @AFADoomer There are some [comments](https://www.moddb.com/members/toomuchcoffee) on ModDB that express dissatisfaction with that you can move the combination safe handle to a position between two numbers, and it could not be easy to determine exactly which of the two numbers the safe will choose. Do you think if it could be reasonable to only do discrete +-1 number changes on the safe wheel with each key press?

I noticed this myself as well, so I was usually "guessing" and it worked for me, but yes, staying exactly on one number to be clear would be cool.

**Comment by Tormentor667** [comment]
> Merge some of the addons into the base game (namely behaviour, more_weapons, and score)? Add unused scrapped frames to actors (crouched firing)?

I'd 'no' this, as I'd like to keep these things as addons.
>

**Comment by AFADoomer** [comment]
The safe treats any position in between the two small lines on either side of the number as that number (really, the code already fudges the range a little bit more if it's the correct next value in the combination).  I'm really not sure what people want here...  you can already move the dial in tiny increments if you just tap the key.

**Comment by Username-N00b-is-not-available** [comment]
What is the current status of issues mentioned in the original post?

**Comment by Tormentor667** [comment]
Updated at least one :)

**Comment by AFADoomer** [comment]
Most of the ACS library that can be transitioned to ZScript has been, with the major exception if the Droplets code.

**Comment by Tormentor667** [comment]
> Fix maps which break a non-cheating playthrough after map cXmX_X (e. g. you cannot finish C2M5_B if warped directly there, as the explosive charges are given in M5_A and not in M5_B; also true for the Firebrand and all maps after it, since you need to have it for C3M6_B. I don't remember if there are other ones)

For this, the operations are meant to be played completely, so you can't just play C2M5_B without playing C2M5_A. If someone cheats to C2M5_B, he can also noclip or cheat himself some explosives.

> Externalize hard-coded data for 'using' wall textures from scripts to a data/config file and generalize implementation

That's the last remaining thing here, but what exactly needs to be done here?

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 There were some features here that you marked as implemented a few minutes ago, but to my information work on some of them has not started yet. Does that mean we are discarding them? Just would like to know for sure.

**Comment by Tormentor667** [comment]
I marked all which are taken care of and which have an own unique issue posted already that needs to be finished.

**Comment by Username-N00b-is-not-available** [comment]
Well, to me there are at least five of them which have not been fixed or addressed in current issues, mostly small nitpicks like the tank MaxStepHeight and indication of jumped-off keys, but then there is ```Remove DECORATE-specific hacks from translated ZScript actor code```...

**Comment by Tormentor667** [comment]
Well can you post unique issues for remaining bugs and issues?
